// images
export { default as BannerBg } from './images/homebanner.webp'
export { default as MobileBannerBg } from './images/mobile-bg.webp'
export { default as logoDark } from './images/logo-dark.png'
export { default as logoWhite } from './images/logo-white.png'
export { default as goldRing } from './images/gold-ring.webp'
export { default as blackRing } from './images/black-ring.webp'
export { default as sliverRing } from './images/silver-ring.webp'
export { default as stealthRing } from './images/stealth-ring.webp'
export { default as roseGold } from './images/rose-gold-ring.webp'
export { default as goldIcon } from './images/gold-icon.webp'
export { default as blackIcon } from './images/black-icon.webp'
export { default as silverIcon } from './images/silver-icon.webp'
export { default as stealthIcon } from './images/stealth-icon.webp'
export { default as roseGoldIcon } from './images/rose-gold-icon.webp'
export { default as washingtonLogo } from './images/washington-post-logo.svg'
export { default as usaTodayLogo } from './images/usa-today-logo.svg'
export { default as architechuralTodayLogo } from './images/architectural-digest-logo.svg'
export { default as homePhone } from './images/home-phone.jpg'
export { default as readinessphone } from './images/readiness-phone.webp'
export { default as runningPhone } from './images/running-phone.webp'
export { default as sleepPhone } from './images/sleep-phone.webp'
export { default as SleepingMan } from './images/sleeping-man.webp'
export { default as fitness } from './images/fitness.jpg'
export { default as readiness } from './images/readiness.jpg'
export { default as girlSleeping } from './images/girl-sleeping-on-mom.webp'
export { default as girlSleepingMobile } from './images/girl-sleeping-on-mom-mobile.webp'
export { default as girlWithTowel } from './images/girl-with-towel.webp'
export { default as girlWithTowelMobile } from './images/girl-with-towel-mobile.webp'
export { default as manWithOura } from './images/man-with-oura.webp'
export { default as manWithOuraMobile } from './images/man-with-oura-mobile.webp'
export { default as manWalking } from './images/man-walking.jpg'
export { default as fingersOnWater } from './images//fingers-water.webp'
export { default as manCalling } from './images/man-calling.avif'
export { default as ringOnRing } from './images/ring-on-ring.webp'
export { default as expertsGotlieb } from './images/experts-gotlieb.jpeg'
export { default as expertsRobbins } from './images/experts-robbins.jpeg'
export { default as mattWalker } from './images/matt-walker.webp'

// icons

export { default as instagram } from './icons/ig.svg'
export { default as twitter } from './icons/twitter.svg'
export { default as facebook } from './icons/facebook.svg'
export { default as youtube } from './icons/youtube.svg'
export { default as tiktok } from './icons/tiktok.svg'
export { default as pinterest } from './icons/pinterest.svg'
export { default as arrowDown } from './icons/arrowDown.svg'
export { default as arrowUp } from './icons/arrowUp.svg'

export { default as accepted } from './icons/accepted.svg'


